---
steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'gcp-rover']
  id: 'go-install'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-rover', '.']
  waitFor: ['go-install']

images: ['gcr.io/$PROJECT_ID/gcp-rover']
