---
steps:
- name: "gcr.io/cloud-builders/go"
  env:  ["PROJECT_ROOT=gcp-rover"]
  args: ["install", "."]
  id:   "go-install"

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/gcp-rover:${TAG_NAME}", "."]
  id:   "docker-build"

images: ["gcr.io/$PROJECT_ID/gcp-rover:${TAG_NAME}"]
