---
kind: Service
apiVersion: v1
metadata:
  name: gcp-rover
  labels:
    app: gcp-rover
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: gcp-rover
  type: LoadBalancer
  loadBalancerSourceRanges:
    - '83.87.224.9/32'      # home
    - '91.195.1.33/32'      # office
    - '10.0.0.0/8'          # internal
