---
kind: Service
apiVersion: v1
metadata:
  name: gcp-rover
  labels:
    app: gcp-rover
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: gcp-rover
  type: LoadBalancer
